invoice/urls.py
from django.urls import path

from . import views

app_name = "invoice"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.InvoiceDetailView.as_view(), name="details"),
    path(
        "<int:pk>/edit",
        views.InvoiceEditFormView.as_view(),
        name="edit_invoice",
    ),
    path(
        "released/<int:pk>/",
        views.ReleasedDetailView.as_view(),
        name="released_details",
    ),
    path(
        "released/<int:pk>/edit",
        views.ReleasedEditFormView.as_view(),
        name="released_edit",
    ),
    path(
        "returned/",
        views.ReturnedCreateFormView.as_view(),
        name="returned_create",
    ),
    path(
        "returned/<int:pk>/",
        views.ReturnedDetailView.as_view(),
        name="returned_details",
    ),
]

invoices/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", include("invoice.urls")),
    path("admin/", admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view()),
]

invoice/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("product_name"))
    price = models.FloatField(verbose_name=_("product_price"))

    class Meta:
        verbose_name = _("product_model")
        verbose_name_plural = _("products_model")

    def __str__(self):
        return f"{self.name}, цена: {self.price}"


class Client(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("client_name"))

    class Meta:
        verbose_name = _("client_model")
        verbose_name_plural = _("clients_model")

    def __str__(self):
        return f"{self.name}"


class Invoice(models.Model):
    number = models.IntegerField(verbose_name=_("invoice_number"))
    date = models.DateField(verbose_name=_("invoice_date"))
    client = models.ForeignKey(
        Client, on_delete=models.CASCADE, verbose_name=_("invoice_client")
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("created_at")
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name=_("updated_at")
    )

    @property
    def released(self):
        return Released.objects.filter(invoice_id=self.id)

    @property
    def summary(self):
        return sum([i.summary for i in self.released])

    @property
    def qty(self):
        return sum([i.qty for i in self.released])

    def __str__(self):
        return f"{self.number} от {self.date} для {self.client}"

    def get_absolute_url(self):
        return reverse("invoice:details", kwargs={"pk": self.pk})


class Released(models.Model):
    invoice = models.ForeignKey(
        Invoice, on_delete=models.CASCADE, verbose_name=_("released_invoice")
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name=_("released_product")
    )
    qty = models.IntegerField(verbose_name=_("released_qty"))
    discount = models.IntegerField(
        default=0, verbose_name=_("released_discount")
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("created_at")
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name=_("updated_at")
    )

    @property
    def summary(self):
        summary = self.product.price * self.qty
        return summary - (summary * self.discount / 100)

    def get_absolute_url(self):
        return reverse("invoice:details", kwargs={"pk": self.invoice.pk})

    def __str__(self):
        return f"{self.product}  кол-во: {self.qty} скидка: {self.discount}%"


class Returned(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name=_("released_product")
    )
    client = models.ForeignKey(
        Client,
        default=None,
        on_delete=models.CASCADE,
        verbose_name=_("invoice_client"),
    )
    qty = models.IntegerField(verbose_name=_("returned_qty"))
    discount = models.IntegerField(
        default=0, verbose_name=_("returned_discount")
    )
    date = models.DateField(verbose_name=_("returned_date"))
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("created_at")
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name=_("updated_at")
    )

    @property
    def summary(self):
        summary = self.product.price * self.qty
        return summary - (summary * self.discount / 100)

    def get_absolute_url(self):
        return reverse("invoice:index")

    def __str__(self):
        return (
            f"Возврат товара: {self.product} "
            f"кол-во: {self.qty} скидка: {self.discount}%"
        )

invoice/views.py
from django import forms
from django.core import serializers
from django.db.models import (
    ExpressionWrapper,
    F,
    FloatField,
    OuterRef,
    Subquery,
    Sum,
    Value,
    Count,
)
from django.db.models.functions import Coalesce
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import generic

from .models import Client, Invoice, Product, Released, Returned


class IndexView(generic.View):

    template_name = "invoice/index.html"

    _count_summary = ExpressionWrapper(
        F("product__price") * F("qty")
        - F("product__price") * F("qty") / 100 * F("discount"),
        output_field=FloatField(),
    )
    _invoices_sorting = ["number", "date", "created_at"]

    def _add_invoice_sorting(self, request, invoices):
        sorting = request.GET.get("sort_invoices", "-created_at")
        return invoices.order_by(sorting)

    def _generate_sorting_list(self, fields: list):
        data = []
        for field in fields:
            f = Invoice._meta.get_field(field)
            name = f.name
            vn = f.verbose_name
            data.append(
                {"value": name, "text": vn, "add_text": _("sorting_asc")}
            )
            data.append(
                {
                    "value": "-" + name,
                    "text": vn,
                    "add_text": _("sorting_desc"),
                }
            )
        return data

    def get(self, request):
        year = request.GET.get("filter_year")
        month = request.GET.get("filter_month")
        if year and month:
            invoices = Invoice.objects.filter(
                date__year=year, date__month=month
            )
            returned = Returned.objects.filter(
                date__year=year, date__month=month
            )
        else:
            invoices = Invoice.objects.all()
            returned = Returned.objects.all()
        invoices = self._add_invoice_sorting(request, invoices)
        returned_subquery = (
            Returned.objects.filter(product=OuterRef("pk"))
            .values("product_id")
            .annotate(
                sum_returned_qty=Sum("qty"),
                sum_returned=Sum(self._count_summary),
            )
        )
        released_subquery = (
            Released.objects.filter(
                product=OuterRef("pk"), invoice__in=invoices
            )
            .values("product_id")
            .annotate(sum_qty=Sum("qty"), sum_summary=Sum(self._count_summary))
        )
        products = Product.objects.annotate(
            sum_qty=Coalesce(
                Subquery(released_subquery.values("sum_qty")), Value(0)
            ),
            sum_summary=Coalesce(
                Subquery(released_subquery.values("sum_summary")), Value(0)
            ),
            sum_returned_qty=Coalesce(
                Subquery(returned_subquery.values("sum_returned_qty")),
                Value(0),
            ),
            sum_returned=Coalesce(
                Subquery(returned_subquery.values("sum_returned")), Value(0)
            ),
            sum_with_returned=F("sum_summary") - F("sum_returned"),
            sum_with_returned_qty=F("sum_qty") - F("sum_returned_qty"),
        ).order_by("name")

        returned_subquery = (
            Returned.objects.filter(client=OuterRef("pk"))
            .values("client_id")
            .annotate(
                sum_returned_qty=Sum("qty"),
                sum_returned=Sum(self._count_summary),
            )
        )
        released_subquery = (
            Released.objects.filter(
                invoice__client=OuterRef("pk"), invoice__in=invoices
            )
            .values("invoice__client__id")
            .annotate(sum_qty=Sum("qty"), sum_summary=Sum(self._count_summary))
        )
        clients = Client.objects.annotate(
            sum_qty=Coalesce(
                Subquery(released_subquery.values("sum_qty")), Value(0)
            ),
            sum_summary=Coalesce(
                Subquery(released_subquery.values("sum_summary")), Value(0)
            ),
            sum_returned_qty=Coalesce(
                Subquery(returned_subquery.values("sum_returned_qty")),
                Value(0),
            ),
            sum_returned=Coalesce(
                Subquery(returned_subquery.values("sum_returned")), Value(0)
            ),
            sum_with_returned=F("sum_summary") - F("sum_returned"),
            sum_with_returned_qty=F("sum_qty") - F("sum_returned_qty"),
            sum_invoices=Coalesce(Count("invoice"), Value(0)),
        ).order_by("name")
        sum_summary = sum([i.summary for i in invoices])
        sum_returned = sum([i.summary for i in returned])
        context = {
            "invoices": invoices,
            "clients": clients,
            "returned": returned,
            "sum_summary": sum_summary,
            "sum_returned": sum_returned,
            "sum_with_returned": sum_summary - sum_returned,
            "products_summary": products,
            "returned_create_form": ReturnedCreateForm(),
            "returned_create_url": reverse("invoice:returned_create"),
            "invoice_sort_fields": self._generate_sorting_list(
                self._invoices_sorting
            ),
        }
        return render(request, self.template_name, context)

    def post(self, request):
        client = get_object_or_404(
            Client, pk=request.POST.get("invoice_client")
        )
        try:
            data = {
                "number": int(
                    request.POST.get("invoice_number")
                    if request.POST.get("invoice_number", "") != ""
                    else 0
                ),
                "date": request.POST.get("invoice_date"),
                "client": client,
            }
        except KeyError:
            return render(
                request,
                self.template_name,
                {"error_message": "Введены неверные данные"},
            )
        else:
            invoice = Invoice(**data)
            invoice.save()
            return HttpResponseRedirect(
                reverse("invoice:details", args=(invoice.id,))
            )


class InvoiceDetailView(generic.DetailView):
    model = Invoice
    template_name = "invoice/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["released"] = Released.objects.filter(invoice=self.object.id)
        context["products"] = Product.objects.order_by("name")
        context["sum_qty"] = sum([i.qty for i in context["released"]])
        context["sum_summary"] = sum([i.summary for i in context["released"]])
        return context

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=request.POST.get("product"))
        invoice = get_object_or_404(Invoice, pk=pk)
        try:
            data = {
                "invoice": invoice,
                "product": product,
                "qty": int(
                    request.POST.get("qty")
                    if request.POST.get("qty", "") != ""
                    else 0
                ),
                "discount": int(
                    request.POST.get("discount")
                    if request.POST.get("discount", "") != ""
                    else 0
                ),
            }
        except KeyError:
            return render(
                request,
                self.template_name,
                {"error_message": "Введены неверные данные"},
            )
        else:
            released = Released(**data)
            released.save()
            return HttpResponseRedirect(reverse("invoice:details", args=(pk,)))

    def put(self, request, pk):
        invoice = get_object_or_404(Invoice, pk=pk)
        client = get_object_or_404(
            Client, pk=request.POST.get("invoice_client")
        )
        try:
            data = {
                "number": int(
                    request.POST.get("invoice_number")
                    if request.POST.get("invoice_number", "") != ""
                    else 0
                ),
                "date": request.POST.get("invoice_date"),
                "client": client,
            }
        except KeyError:
            return render(
                request,
                self.template_name,
                {"error_message": "Введены неверные данные"},
            )
        else:
            for key, value in data.items():
                setattr(invoice, key, value)
            invoice.save()
            return HttpResponseRedirect(reverse("invoice:details", args=(pk,)))

    def delete(self, request, pk):
        invoice = get_object_or_404(Invoice, pk=pk)
        invoice.delete()
        return HttpResponse("OK")


class ReleasedDetailView(generic.DetailView):
    model = Released
    template_name = "invoice/released.html"

    def delete(self, request, pk):
        released = get_object_or_404(Released, pk=pk)
        released.delete()
        return HttpResponse("OK")


class InvoiceEditFormView(generic.UpdateView):
    model = Invoice
    fields = ["number", "date", "client"]
    template_name_suffix = "EditForm"


class ReleasedEditFormView(generic.UpdateView):
    model = Released
    fields = ["product", "qty", "discount"]
    template_name_suffix = "EditForm"


class ReturnedCreateForm(forms.ModelForm):
    class Meta:
        model = Returned
        fields = ["product", "qty", "discount", "date", "client"]


class ReturnedCreateFormView(generic.CreateView):
    model = Returned
    fields = ["product", "qty", "discount", "date", "client"]

    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse("invoice:index"))


class ReturnedDetailView(generic.DetailView):
    model = Returned
    template_name = "invoice/returned.html"

invoice/templates/invoice/detail.html
{% extends "base.html" %}

{% block breadcrumb %}

<li class="nav-item">
    <a class="nav-link active" href="{% url 'invoice:details' invoice.id %}">Накладная {{ invoice.number }} от {{ invoice.date }} для {{ invoice.client.name }}</a>
</li>

{% endblock breadcrumb %}

{% block content %}

{% include "invoice/components/deleteInvoiceModal.html" with invoice=invoice %}

    <h1 class="mt-2">
        Накладная {{ invoice.number }} от {{ invoice.date }} для {{ invoice.client.name }}
        <small class="">
            <a href="#" data-toggle="modal" data-target="#deleteInvoiceModal{{ invoice.id }}"><i class="far fa-times-circle float-right text-danger"></i></a>
            <a href="{% url 'invoice:edit_invoice' invoice.id %}"><i class="fas fa-pen float-right text-warning"></i></a>
        </small>
    </h1>

    <div class="card mb-2">
        <div class="card-body">
    <form action="{% url 'invoice:details' invoice.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="invoice_number" id="invoice_number" value="{{ invoice.id }}">
        <div class="form-row">
            <div class="form-group mx-1 mb-0">
                <select class="form-control" id="product" name="product">
                    {% for product in products %}
                    <option value="{{ product.id }}">{{ product.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group mx-1 mb-0">
                <input class="form-control" type="number" name="qty" id="qty" placeholder="Количество">
            </div>
            <div class="form-group mx-1 mb-0">
                <input class="form-control" type="number" name="discount" id="discount" placeholder="Скидка">
            </div>
            <div class="form-group mx-1 mb-0">
                <input class="form-control btn btn-primary" type="submit" value="Добавить">
            </div>
        </div>
    </form>
        </div>
    </div>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th class="tg-0lax">№</th>
            <th class="tg-0lax">Наименование</th>
            <th class="tg-0lax">Кол-во</th>
            <th class="tg-0lax">Скидка</th>
            <th class="tg-0lax">Цена</th>
            <th class="tg-0lax">Сумма</th>
            <th class="tg-0lax">Ссылка</th>
        </tr>
        </thead>
    {% for release in released %}

        <tr>
            <td class="tg-0lax">{{ forloop.counter }}</td>
            <td class="tg-0lax">{{ release.product.name }}</td>
            <td class="tg-0lax">{{ release.qty }}</td>
            <td class="tg-0lax">{{ release.discount }}</td>
            <td class="tg-0lax">{{ release.product.price }}</td>
            <td class="tg-0lax">{{ release.summary }}</td>
            <td class="tg-0lax">
                <a href="{% url 'invoice:released_details' release.id %}"><i class="fas fa-info-circle text-primary"></i></a>
                <a href="{% url 'invoice:released_edit' release.id %}"><i class="fas fa-pen text-warning"></i></a>
                <a href="#" onclick="delete_released('{{ release.id }}', '{{ invoice.id }}')"><i class="far fa-times-circle text-danger"></i></a>
            </td>
        </tr>
    {% empty %}
        <tr><td colspan="7">Накладная пуста</td></tr>
    {% endfor %}
    {% if released %}
        <tr>
            <td colspan="2">Итого</td>
            <td class="table-primary">{{ sum_qty }}</td>
            <td ></td>
            <td ></td>
            <td class="table-primary">{{ sum_summary }}</td>
            <td ></td>
        </tr>
    {% endif %}
    </table>

{% endblock %}

invoice/templates/invoice/index.html
{% extends "base.html" %}


{% block navbar_addition %}

<form class="form-inline my-2 my-lg-0 float-right">
        <small class="mr-2" id="filter-addon">Фильтр</small>
        <input class="form-control form-control-sm" aria-describedby="filter-addon" type="month" id="filter_month" placeholder="Месяц" style="width:150px;"/>
        <button class="btn btn-sm btn-outline-success" onclick="set_query_params()" type="button">
            <i class="fas fa-check"></i>
        </button>
        <button class="btn btn-sm btn-outline-warning" onclick="clear_params()" type="button">
            <i class="fas fa-times-circle"></i>
        </button>
</form>

{% endblock navbar_addition %}

{% block content %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <div class="row">
        <div class="col-md-3">
            <ul>
                <li>Общая сумма: {{ sum_summary }}</li>
                <li>Сумма возвратов {{ sum_returned }}</li>
                <li>Итог: {{ sum_with_returned }}</li>
            </ul>
        </div>
        <div class="col-md-9">
            <div class="accordion my-2 w-75 mx-auto" id="accordionAdding">
                {% include "invoice/components/addingInvoiceForm.html" %}
                {% include "invoice/components/basicAccordionForm.html" with form=returned_create_form submit_text="Создать" collapse_name="createReturned" form_name="Добавить возврат" url=returned_create_url %}
            </div>
        </div>
    </div>



    <ul class="nav nav-tabs" id="mainPageTabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="main-list-tab" data-toggle="tab" href="#main-list" role="tab" aria-controls="home" aria-selected="true">Список накладных</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="products-tab" data-toggle="tab" href="#products" role="tab" aria-controls="profile" aria-selected="false">Продукция</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="clients-tab" data-toggle="tab" href="#clients" role="tab" aria-controls="contact" aria-selected="false">Клиенты</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="returned-tab" data-toggle="tab" href="#returned" role="tab" aria-controls="returned" aria-selected="false">Возвраты</a>
      </li>
    </ul>

    <div class="tab-content p-2 border-left border-right border-bottom" id="mainPageTabsContent">

        <div class="tab-pane fade show active" id="main-list" role="tabpanel" aria-labelledby="main-list-tab">

            {% include "invoice/components/sortSelectionForm.html" with data=invoice_sort_fields sort_name="sort_invoices" %}

            <table class="table table-sm table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                    <th>№</th>
                    <th>Номер накладной</th>
                    <th>Дата</th>
                    <th>Клиент</th>
                    <th>Кол-во</th>
                    <th>Сумма</th>
                    <th>Действия</th>
                </tr>
                </thead>
        {% for invoice in invoices %}
                <tr>
                {% include "invoice/components/deleteInvoiceModal.html" with invoice=invoice %}
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <a href="{% url 'invoice:details' invoice.id %}">
                            Накладная {{ invoice.number }}
                        </a>
                    </td>
                    <td>{{ invoice.date }}</td>
                    <td>{{ invoice.client }}</td>
                    <td>{{ invoice.qty }}</td>
                    <td>{{ invoice.summary }}</td>
                    <td>
                        <a href="{% url 'invoice:edit_invoice' invoice.id %}">
                            <i class="fas fa-pen text-warning"></i>
                        </a>
                        <a href="#" data-toggle="modal" data-target="#deleteInvoiceModal{{ invoice.id }}">
                            <i class="far fa-times-circle text-danger"></i>
                        </a>
                    </td>
                </tr>
        {% empty %}
                <tr><td colspan="8">Недостаточно информации</td></tr>
        {% endfor %}
            </table>
        </div>
        <div class="tab-pane fade" id="products" role="tabpanel" aria-labelledby="products-tab">
            <table class="table table-sm table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                    <th>№</th>
                    <th>Наименование</th>
                    <th>Кол-во</th>
                    <th>Сумма</th>
{#                    <th>Возврат кол-во</th>#}
{#                    <th>Возврат сумма</th>#}
{#                    <th>Итог кол-во</th>#}
{#                    <th>Итог сумма</th>#}
                </tr>
                </thead>
        {% for product in products_summary %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.sum_qty }}</td>
                    <td>{{ product.sum_summary }}</td>
{#                    <td>{{ product.sum_returned_qty }}</td>#}
{#                    <td>{{ product.sum_returned }}</td>#}
{#                    <td>{{ product.sum_with_returned_qty }}</td>#}
{#                    <td>{{ product.sum_with_returned }}</td>#}
                </tr>
        {% empty %}
                <tr><td colspan="8">Недостаточно информации</td></tr>
        {% endfor %}
            </table>
        </div>

        <div class="tab-pane fade" id="clients" role="tabpanel" aria-labelledby="clients-tab">
            <table class="table table-sm table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                    <th>№</th>
                    <th>Клиент</th>
                    <th>Количество накладных</th>
                    <th>Кол-во товара</th>
                    <th>Сумма</th>
{#                    <th>Возврат кол-во</th>#}
{#                    <th>Возврат сумма</th>#}
{#                    <th>Итог кол-во</th>#}
{#                    <th>Итог сумма</th>#}
                </tr>
                </thead>

        {% for client in clients %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ client.name }}</td>
                    <td>{{ client.sum_invoices }}</td>
                    <td>{{ client.sum_qty }}</td>
                    <td>{{ client.sum_summary }}</td>
{#                    <td>{{ client.sum_returned_qty }}</td>#}
{#                    <td>{{ client.sum_returned }}</td>#}
{#                    <td>{{ client.sum_with_returned_qty }}</td>#}
{#                    <td>{{ client.sum_with_returned }}</td>#}
                </tr>
        {% endfor %}
            </table>
        </div>

        <div class="tab-pane fade" id="returned" role="tabpanel" aria-labelledby="returned-tab">
            <table class="table table-sm table-bordered table-hover">
                <thead class="thead-light">
                <tr>
                    <th>№</th>
                    <th>Наименование</th>
                    <th>Дата</th>
                    <th>Кол-во</th>
                    <th>Сумма</th>
                    <th>Действие</th>
                    <th>Клиент</th>
                </tr>
                </thead>

        {% for return in returned %}
                <tr>
                    {% include "invoice/components/deleteReturnedModal.html" with returned=return %}
                    <td>{{ forloop.counter }}</td>
                    <td>{{ return.product }}</td>
                    <td>{{ return.date }}</td>
                    <td>{{ return.qty }}</td>
                    <td>{{ return.summary }}</td>
                    <td>{{ return.client }}</td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#deleteReturnedModal{{ return.id }}">
                            <i class="far fa-times-circle float-right text-danger"></i>
                        </a>
                    </td>
                </tr>
        {% empty %}
                <tr><td colspan="7">Недостаточно информации</td></tr>
        {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}

invoice/templates/invoice/invoiceEditForm.html
{% extends "base.html" %}

{% block content %}

{% include "invoice/components/basicForm.html" with form=form submit_text="Обновить" %}

{% endblock %}

invoice/templates/invoice/released.html
{% extends "base.html" %}

{% block content %}

    <h1>Отпущено:</h1>
    <p>
        <br />Накладная: {{ released.invoice }}
        <br />Наименование: {{ released.product.name }}
        <br />Количество: {{ released.qty }}
    </p>

{% endblock %}

invoice/templates/invoice/releasedEditForm.html
{% extends "base.html" %}

{% block content %}

{% include "invoice/components/basicForm.html" with form=form submit_text="Обновить" %}

{% endblock %}

invoice/templates/invoice/returned.html
{% extends "base.html" %}

{% block content %}

    <h1>Возврат:</h1>
    <p>
        <br />Наименование: {{ returned.product.name }}
        <br />Дата: {{ returned.date }}
        <br />Количество: {{ returned.qty }}
        <br />Скидка: {{ returned.discount }}
        <br />Сумма: {{ returned.summary }}
    </p>

{% endblock %}