invoice/urls.py
from django.urls import path

from . import views

app_name = "invoice"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.InvoiceDetailView.as_view(), name="details"),
    path(
        "<int:pk>/edit",
        views.InvoiceEditFormView.as_view(),
        name="edit_invoice",
    ),
    path(
        "released/<int:pk>/",
        views.ReleasedDetailView.as_view(),
        name="released_details",
    ),
    path(
        "released/<int:pk>/edit",
        views.ReleasedEditFormView.as_view(),
        name="released_edit",
    ),
    path(
        "returned/",
        views.ReturnedCreateFormView.as_view(),
        name="returned_create",
    ),
    path(
        "returned/<int:pk>/",
        views.ReturnedDetailView.as_view(),
        name="returned_details",
    ),
]

invoices/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", include("invoice.urls")),
    path("admin/", admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view()),
]

invoice/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("product_name"))
    price = models.FloatField(verbose_name=_("product_price"))

    class Meta:
        verbose_name = _("product_model")
        verbose_name_plural = _("products_model")

    def __str__(self):
        return f"{self.name}, цена: {self.price}"


class Client(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("client_name"))

    class Meta:
        verbose_name = _("client_model")
        verbose_name_plural = _("clients_model")

    def __str__(self):
        return f"{self.name}"


class Invoice(models.Model):
    number = models.IntegerField(verbose_name=_("invoice_number"))
    date = models.DateField(verbose_name=_("invoice_date"))
    client = models.ForeignKey(
        Client, on_delete=models.CASCADE, verbose_name=_("invoice_client")
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("created_at")
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name=_("updated_at")
    )

    @property
    def released(self):
        return Released.objects.filter(invoice_id=self.id)

    @property
    def summary(self):
        return sum([i.summary for i in self.released])

    @property
    def qty(self):
        return sum([i.qty for i in self.released])

    def __str__(self):
        return f"{self.number} от {self.date} для {self.client}"

    def get_absolute_url(self):
        return reverse("invoice:details", kwargs={"pk": self.pk})


class Released(models.Model):
    invoice = models.ForeignKey(
        Invoice, on_delete=models.CASCADE, verbose_name=_("released_invoice")
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name=_("released_product")
    )
    qty = models.IntegerField(verbose_name=_("released_qty"))
    discount = models.IntegerField(
        default=0, verbose_name=_("released_discount")
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("created_at")
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name=_("updated_at")
    )

    @property
    def summary(self):
        summary = self.product.price * self.qty
        return summary - (summary * self.discount / 100)

    def get_absolute_url(self):
        return reverse("invoice:details", kwargs={"pk": self.invoice.pk})

    def __str__(self):
        return f"{self.product}  кол-во: {self.qty} скидка: {self.discount}%"


class Returned(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name=_("released_product")
    )
    client = models.ForeignKey(
        Client,
        default=None,
        on_delete=models.CASCADE,
        verbose_name=_("invoice_client"),
    )
    qty = models.IntegerField(verbose_name=_("returned_qty"))
    discount = models.IntegerField(
        default=0, verbose_name=_("returned_discount")
    )
    date = models.DateField(verbose_name=_("returned_date"))
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("created_at")
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name=_("updated_at")
    )

    @property
    def summary(self):
        summary = self.product.price * self.qty
        return summary - (summary * self.discount / 100)

    def get_absolute_url(self):
        return reverse("invoice:index")

    def __str__(self):
        return (
            f"Возврат товара: {self.product} "
            f"кол-во: {self.qty} скидка: {self.discount}%"
        )

invoice/views.py
from django import forms
from django.core import serializers
from django.db.models import (
    ExpressionWrapper,
    F,
    FloatField,
    OuterRef,
    Subquery,
    Sum,
    Value,
    Count,
)
from django.db.models.functions import Coalesce
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import generic

from .models import Client, Invoice, Product, Released, Returned


class IndexView(generic.View):

    template_name = "invoice/index.html"

    _count_summary = ExpressionWrapper(
        F("product__price") * F("qty")
        - F("product__price") * F("qty") / 100 * F("discount"),
        output_field=FloatField(),
    )
    _invoices_sorting = ["number", "date", "created_at"]

    def _add_invoice_sorting(self, request, invoices):
        sorting = request.GET.get("sort_invoices", "-created_at")
        return invoices.order_by(sorting)

    def _generate_sorting_list(self, fields: list):
        data = []
        for field in fields:
            f = Invoice._meta.get_field(field)
            name = f.name
            vn = f.verbose_name
            data.append(
                {"value": name, "text": vn, "add_text": _("sorting_asc")}
            )
            data.append(
                {
                    "value": "-" + name,
                    "text": vn,
                    "add_text": _("sorting_desc"),
                }
            )
        return data

    def get(self, request):
        year = request.GET.get("filter_year")
        month = request.GET.get("filter_month")
        if year and month:
            invoices = Invoice.objects.filter(
                date__year=year, date__month=month
            )
            returned = Returned.objects.filter(
                date__year=year, date__month=month
            )
        else:
            invoices = Invoice.objects.all()
            returned = Returned.objects.all()
        invoices = self._add_invoice_sorting(request, invoices)
        returned_subquery = (
            Returned.objects.filter(product=OuterRef("pk"))
            .values("product_id")
            .annotate(
                sum_returned_qty=Sum("qty"),
                sum_returned=Sum(self._count_summary),
            )
        )
        released_subquery = (
            Released.objects.filter(
                product=OuterRef("pk"), invoice__in=invoices
            )
            .values("product_id")
            .annotate(sum_qty=Sum("qty"), sum_summary=Sum(self._count_summary))
        )
        products = Product.objects.annotate(
            sum_qty=Coalesce(
                Subquery(released_subquery.values("sum_qty")), Value(0)
            ),
            sum_summary=Coalesce(
                Subquery(released_subquery.values("sum_summary")), Value(0)
            ),
            sum_returned_qty=Coalesce(
                Subquery(returned_subquery.values("sum_returned_qty")),
                Value(0),
            ),
            sum_returned=Coalesce(
                Subquery(returned_subquery.values("sum_returned")), Value(0)
            ),
            sum_with_returned=F("sum_summary") - F("sum_returned"),
            sum_with_returned_qty=F("sum_qty") - F("sum_returned_qty"),
        ).order_by("name")

        returned_subquery = (
            Returned.objects.filter(client=OuterRef("pk"))
            .values("client_id")
            .annotate(
                sum_returned_qty=Sum("qty"),
                sum_returned=Sum(self._count_summary),
            )
        )
        released_subquery = (
            Released.objects.filter(
                invoice__client=OuterRef("pk"), invoice__in=invoices
            )
            .values("invoice__client__id")
            .annotate(sum_qty=Sum("qty"), sum_summary=Sum(self._count_summary))
        )
        clients = Client.objects.annotate(
            sum_qty=Coalesce(
                Subquery(released_subquery.values("sum_qty")), Value(0)
            ),
            sum_summary=Coalesce(
                Subquery(released_subquery.values("sum_summary")), Value(0)
            ),
            sum_returned_qty=Coalesce(
                Subquery(returned_subquery.values("sum_returned_qty")),
                Value(0),
            ),
            sum_returned=Coalesce(
                Subquery(returned_subquery.values("sum_returned")), Value(0)
            ),
            sum_with_returned=F("sum_summary") - F("sum_returned"),
            sum_with_returned_qty=F("sum_qty") - F("sum_returned_qty"),
            sum_invoices=Coalesce(Count("invoice"), Value(0)),
        ).order_by("name")
        sum_summary = sum([i.summary for i in invoices])
        sum_returned = sum([i.summary for i in returned])
        context = {
            "invoices": invoices,
            "clients": clients,
            "returned": returned,
            "sum_summary": sum_summary,
            "sum_returned": sum_returned,
            "sum_with_returned": sum_summary - sum_returned,
            "products_summary": products,
            "returned_create_form": ReturnedCreateForm(),
            "returned_create_url": reverse("invoice:returned_create"),
            "invoice_sort_fields": self._generate_sorting_list(
                self._invoices_sorting
            ),
        }
        return render(request, self.template_name, context)

    def post(self, request):
        client = get_object_or_404(
            Client, pk=request.POST.get("invoice_client")
        )
        try:
            data = {
                "number": int(
                    request.POST.get("invoice_number")
                    if request.POST.get("invoice_number", "") != ""
                    else 0
                ),
                "date": request.POST.get("invoice_date"),
                "client": client,
            }
        except KeyError:
            return render(
                request,
                self.template_name,
                {"error_message": "Введены неверные данные"},
            )
        else:
            invoice = Invoice(**data)
            invoice.save()
            return HttpResponseRedirect(
                reverse("invoice:details", args=(invoice.id,))
            )


class InvoiceDetailView(generic.DetailView):
    model = Invoice
    template_name = "invoice/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["released"] = Released.objects.filter(invoice=self.object.id)
        context["products"] = Product.objects.order_by("name")
        context["sum_qty"] = sum([i.qty for i in context["released"]])
        context["sum_summary"] = sum([i.summary for i in context["released"]])
        return context

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=request.POST.get("product"))
        invoice = get_object_or_404(Invoice, pk=pk)
        try:
            data = {
                "invoice": invoice,
                "product": product,
                "qty": int(
                    request.POST.get("qty")
                    if request.POST.get("qty", "") != ""
                    else 0
                ),
                "discount": int(
                    request.POST.get("discount")
                    if request.POST.get("discount", "") != ""
                    else 0
                ),
            }
        except KeyError:
            return render(
                request,
                self.template_name,
                {"error_message": "Введены неверные данные"},
            )
        else:
            released = Released(**data)
            released.save()
            return HttpResponseRedirect(reverse("invoice:details", args=(pk,)))

    def put(self, request, pk):
        invoice = get_object_or_404(Invoice, pk=pk)
        client = get_object_or_404(
            Client, pk=request.POST.get("invoice_client")
        )
        try:
            data = {
                "number": int(
                    request.POST.get("invoice_number")
                    if request.POST.get("invoice_number", "") != ""
                    else 0
                ),
                "date": request.POST.get("invoice_date"),
                "client": client,
            }
        except KeyError:
            return render(
                request,
                self.template_name,
                {"error_message": "Введены неверные данные"},
            )
        else:
            for key, value in data.items():
                setattr(invoice, key, value)
            invoice.save()
            return HttpResponseRedirect(reverse("invoice:details", args=(pk,)))

    def delete(self, request, pk):
        invoice = get_object_or_404(Invoice, pk=pk)
        invoice.delete()
        return HttpResponse("OK")


class ReleasedDetailView(generic.DetailView):
    model = Released
    template_name = "invoice/released.html"

    def delete(self, request, pk):
        released = get_object_or_404(Released, pk=pk)
        released.delete()
        return HttpResponse("OK")


class InvoiceEditFormView(generic.UpdateView):
    model = Invoice
    fields = ["number", "date", "client"]
    template_name_suffix = "EditForm"


class ReleasedEditFormView(generic.UpdateView):
    model = Released
    fields = ["product", "qty", "discount"]
    template_name_suffix = "EditForm"


class ReturnedCreateForm(forms.ModelForm):
    class Meta:
        model = Returned
        fields = ["product", "qty", "discount", "date", "client"]


class ReturnedCreateFormView(generic.CreateView):
    model = Returned
    fields = ["product", "qty", "discount", "date", "client"]

    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse("invoice:index"))


class ReturnedDetailView(generic.DetailView):
    model = Returned
    template_name = "invoice/returned.html"

invoice/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Накладные</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://yastatic.net/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://use.fontawesome.com/releases/v5.9.0/js/all.js" data-auto-replace-svg="nest"></script>
        <script>
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            function csrfSafeMethod(method) {
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", jQuery("[name=csrfmiddlewaretoken]").val() ? jQuery("[name=csrfmiddlewaretoken]").val():getCookie('csrftoken'));
                    }
                }
            });

            function delete_invoice(id) {
                var url = "{% url 'invoice:details' 0 %}".replace("0", id);

                $.ajax({
                    url: url,
                    type: 'DELETE',
                    success: function(result) {
                        window.location.href = "{% url 'invoice:index' %}";
                    }
                });
            }

            function delete_returned(id) {
                var url = "{% url 'invoice:returned_details' 0 %}".replace("0", id);

                $.ajax({
                    url: url,
                    type: 'DELETE',
                    success: function(result) {
                        window.location.href = "{% url 'invoice:index' %}";
                    }
                });
            }

            function delete_released(id, invoice_id) {
                var url = "{% url 'invoice:released_details' 0 %}".replace("0", id);

                $.ajax({
                    url: url,
                    type: 'DELETE',
                    success: function(result) {
                        window.location.href = "{% url 'invoice:index' %}" + invoice_id;
                    }
                });
            }

            function clear_params() {
                document.getElementById('filter_month').value = "";
                set_query_params();
            }

            function load_query_params() {
                if (document.getElementById('filter_month')){
                    var searchParams = new URLSearchParams(window.location.search);
                    var year = searchParams.get('filter_year');
                    var month = searchParams.get('filter_month');
                    if (year && month){
                    document.getElementById('filter_month').value = year + '-' + month;
                    }
                }
            }

            function set_query_params() {
                var searchParams = new URLSearchParams(window.location.search);
                searchParams.delete('filter_year');
                searchParams.delete('filter_month');
                var values = document.getElementById('filter_month').value.split('-');
                if (values[0] !== ''){
                    searchParams.set('filter_year', values[0]);
                    searchParams.set('filter_month', values[1]);
                }
                window.location.search = searchParams.toLocaleString();
            }

            window.onload = function() {
               load_query_params();

               // Javascript to enable link to tab
                var hash = document.location.hash;
                if (hash) {
                    console.log(hash);
                    $(".nav-tabs a[href=\\"+hash+"]").tab('show');
                }

                // Change hash for page-reload
                $('.nav-tabs a').on('shown.bs.tab', function (e) {
                    window.location.hash = e.target.hash;
                });
            }
        </script>
    </head>

    <body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#"><i class="fas fa-file-invoice text-primary"></i> inVoice</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="/">Главная</a>
              </li>
              {% block breadcrumb %}{% endblock breadcrumb %}
            </ul>
            {% block navbar_addition %}{% endblock navbar_addition %}
          </div>
        </nav>
    {% block content %}{% endblock content %}
    </div>
    </body>
</html>